# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 23:11
from __future__ import unicode_literals

import configuration.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('YT', 'YouTube'), ('FB', 'Facebook'), ('TW', 'Twitter'), ('IN', 'Linkedin')], max_length=50)),
                ('url', models.URLField(help_text='Use Network URL. Ex: https://www.linkedin.com/locomotion-usa', max_length=160)),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'website_networks',
                'verbose_name': 'network',
                'verbose_name_plural': 'networks',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(default='Locomotion USA', max_length=50, unique=True)),
                ('slug', models.SlugField(editable=False)),
                ('slogan', models.CharField(default='Animation & Interactive', max_length=120)),
                ('description', models.CharField(default='Here some description used in footer section', max_length=120)),
                ('header_video_poster', models.FileField(upload_to=configuration.models.website_directory_images_path)),
                ('header_video', models.FileField(blank=True, null=True, upload_to=configuration.models.website_directory_videos_path)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-sitename'],
                'db_table': 'website_configuration',
                'verbose_name': 'configuration',
                'verbose_name_plural': 'global settings',
            },
        ),
        migrations.AddField(
            model_name='socialnetworks',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Website'),
        ),
    ]
