# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Use a short name, max length permitted = 50', max_length=50, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('resume_info', models.TextField(help_text='Describe briefly about service, max length is 250 characters', max_length=250)),
                ('picture', models.ImageField(upload_to=services.models.website_directory_services_path)),
                ('is_public', models.BooleanField(default=False)),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Page')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'website_services',
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
    ]
