# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-28 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('description', models.TextField(max_length=120)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'blog_categories',
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=160, null=True, unique=True, verbose_name='slug')),
                ('page_content', models.TextField(blank=True, null=True, verbose_name='page_content')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_menu', models.BooleanField(default=True, verbose_name='navigation menu')),
                ('category', models.ManyToManyField(blank=True, db_table='blog_page_category_related', to='blog.Category')),
            ],
            options={
                'ordering': ['-title'],
                'db_table': 'blog_pages',
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
            },
        ),
    ]
