# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(editable=False)),
                ('cover', models.ImageField(height_field='height_field', upload_to=portfolio.models.portfolio_directory_path, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('as_promo', models.BooleanField(default=False, verbose_name='Show as Promotional Project')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Page')),
            ],
            options={
                'ordering': ['-name'],
                'db_table': 'website_portfolio',
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project')),
            ],
            options={
                'db_table': 'website_portfolio_promo',
            },
        ),
    ]
